name 'servicenow'
maintainer 'Dennis Whitney'
maintainer_email 'denniswhitney@irunasroot.com'
license 'All Rights Reserved'
description 'Cookbook recipes, modules, and plugins that help manage ServiceNow'
version '0.1.0'
chef_version '>= 16.0'
issues_url 'https://github.com/irunasroot/chef-servicenow/issues'
source_url 'https://github.com/irunasroot/chef-servicenow/'
